<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Atlas.Blazor" />
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="DbcView">
      <HintPath>..\..\src\DbcView\bin\$(Configuration)\net6.0\DbcView.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\samples\bmw_e9x_e8x.dbc"
          Link="Samples\bmw_e9x_e8x.dbc"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
